[project]
name = "flib"
version = "0.1.0"
description = ""
authors = [
    { name = "acordier", email = "acordier@fonctionlabs.com" },
    { name = "mcordier", email = "mcordier@fonctionlabs.com" },
    { name = "jvassalo", email = "jvassalo@fonctionlabs.com" },
]
requires-python = "~=3.10"
readme = "README.md"
dependencies = [
    "qdrant-client>=1.9.0,<2",
    "openai>=1.23.6,<2",
    "pillow>=10.3.0,<11",
    "boto3>=1.34.94,<2",
    "joblib>=1.4.2,<2",
    "ollama>=0.2.0,<0.3",
    "azure-ai-inference>=1.0.0b9,<2",
]

[project.optional-dependencies]
extra-clip = [
    "torch>=2.2.2,<3",
    "torchvision>=0.17.2,<0.18",
]
extra-sam = [
    "segment-anything~=1.0",
    "segment-anything-fast>=0.1.2,<0.2",
    "torch>=2.2.2,<3",
    "torchvision>=0.17.2,<0.18",
    "opencv-python>=4.9.0.80,<5",
    "matplotlib>=3.8.4,<4",
]

[dependency-groups]
dev = [
    "mypy>=1.10.0,<2",
    "pytest>=8.3.3,<9",
]

[tool.hatch.build.targets.sdist]
include = ["flib"]

[tool.hatch.build.targets.wheel]
include = ["flib"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.mypy]
ignore_missing_imports = true
